"use strict";
console.log("-".repeat(80));
console.log(5 + 3);
console.log("-".repeat(80));
console.log(9 - 1);
console.log("-".repeat(80));
console.log(4 * 2);
console.log("-".repeat(80));
console.log(16 / 2);
console.log("-".repeat(80));
